@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant PlayerNameInput
participant LeaderboardManager
participant Leaderboard
participant HeslingtonHustle
participant EndScreen
PlayerNameInput -> PlayerNameInput: Creates LeaderboardManager
LeaderboardManager -> LeaderboardManager: Loads and sorts\nleaderboard file data
PlayerNameInput -> PlayerNameInput: Saves player's name\nto LeaderboardManager
PlayerNameInput -> HeslingtonHustle: Updates state to LEADERBOARD
EndScreen <- HeslingtonHustle: Calls getExamScore()
EndScreen -> HeslingtonHustle: Returns player's score
HeslingtonHustle -> LeaderboardManager: Calls getLeaderboardManager()
LeaderboardManager -> HeslingtonHustle: Returns LeaderboardManager object
HeslingtonHustle -> Leaderboard: Passes LeaderboardManager\nand player score
HeslingtonHustle -> Leaderboard: Sets screen to leaderboard
Leaderboard -> LeaderboardManager: Calls addEntry()
LeaderboardManager -> LeaderboardManager: Saves player's name\nand score to disk
Leaderboard -> LeaderboardManager: Requests rankings
LeaderboardManager -> Leaderboard: Returns top 10 ranking
Leaderboard -> Leaderboard: Displays leaderboard to player
Leaderboard -> HeslingtonHustle: Updates game state to either\nMAIN_MENU or quits
@enduml